permalink: /:year/:month/:day/:title.html
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      entity: Infosec Jerk
      site_author: Infosec Jerk
      site_description: Infosec Jerk
      title: Infosec Jerk
      subtitle: Secure AI Agency
      quip: Automation.  Efficiency.  Uncertain Science.
      logo_url: https://avatars.githubusercontent.com/u/276657749
      layout_css: /www/css/layout.css
      style_css: /www/css/style.css